global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Containers VM'
    static_configs:
      - targets: ['192.168.69.202:9100']

  - job_name: 'Jenkins VM'
    static_configs:
      - targets: ['192.168.69.203:9100']
  - job_name: 'Docker'
    static_configs:
      - targets: ['192.168.69.202:9323']
